name: Node.js CI Workflow

on:
  push:
    branches:
      - '*'  # Trigger workflow on push to any branch
  pull_request:
    branches:
      - '*'  # Trigger workflow on pull request to any branch

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies (CI)
        run: npm ci
        continue-on-error: true

      - name: Install Dependencies (Fallback)
        if: failure()
        run: npm install

      - name: Run Linting
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Build Project
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/

  # Optional: Future-proofing for separate deploy or staging jobs
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build_and_test
  #   steps:
  #     - name: Deploy Project
  #       run: echo 'Deploying...
